<a href="https://colab.research.google.com/github/safeedha/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
import numpy as np
M1=np.array([[1,2,3],[2,3,4],[4,5,6]])
M2=np.array([[1,7,3],[8,7,4],[9,5,6]])
M3=M2.dot(M1)
print(M3)
M4=M3.transpose()
print(M4)

[[27 38 49]
 [38 57 76]
 [43 63 83]]
[[27 38 43]
 [38 57 63]
 [49 76 83]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [2]:
 
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
print("Numpy Matrix is:")
print(n_array)
det = np.linalg.det(n_array) 
print("\nDeterminant of given 3X3 square matrix:")
print(int(det))

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Determinant of given 3X3 square matrix:
137180
