<a href="https://colab.research.google.com/github/safeedha/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
a = np.random.rand(3,3)
print(a)

[[0.90773377 0.8888609  0.97482427]
 [0.31330309 0.56754381 0.88973671]
 [0.93027056 0.58826052 0.79852303]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this 
import numpy as np
a= np.random.rand(4,4)
print('i)',a)
b = np.random.rand(4,4)
print(b)
a = a.reshape(2,8)
b = b.reshape(2,8)
print('ii)',a)
print(b)
print('iii)',np.vstack((a,b)))
print('iv)',np.hstack((a,b)))

i) [[0.96051611 0.71291489 0.00957362 0.83226337]
 [0.88428959 0.55429415 0.34505569 0.67116071]
 [0.23254935 0.60770875 0.83335421 0.14054317]
 [0.44850285 0.13266614 0.8443271  0.72791184]]
[[0.76006465 0.52445703 0.41400388 0.00664814]
 [0.78870225 0.7139891  0.09497049 0.78041357]
 [0.55445881 0.27588565 0.86377148 0.47733938]
 [0.97823943 0.00275425 0.4183779  0.64700092]]
ii) [[0.96051611 0.71291489 0.00957362 0.83226337 0.88428959 0.55429415
  0.34505569 0.67116071]
 [0.23254935 0.60770875 0.83335421 0.14054317 0.44850285 0.13266614
  0.8443271  0.72791184]]
[[0.76006465 0.52445703 0.41400388 0.00664814 0.78870225 0.7139891
  0.09497049 0.78041357]
 [0.55445881 0.27588565 0.86377148 0.47733938 0.97823943 0.00275425
  0.4183779  0.64700092]]
iii) [[0.96051611 0.71291489 0.00957362 0.83226337 0.88428959 0.55429415
  0.34505569 0.67116071]
 [0.23254935 0.60770875 0.83335421 0.14054317 0.44850285 0.13266614
  0.8443271  0.72791184]
 [0.76006465 0.52445703 0.41400388 0.00664814 0.788